@echo off
echo Starting Cryo REPL...
docker run -it --rm -v "%cd%":/src -w //src cryo-toolchain bash -c "cryoc tools/repl.cryo && clang++ -O0 -Wno-override-module tools/repl.cryo.ll /usr/lib/libruntime_cryo.a -o tools/repl -lpthread -ldl && ./tools/repl"
